default:
  date:
    from: '2015-01-01'
    to: '2025-05-02'
  ticker: 'SPY'
  timeframe: '1min'
  direction: 'short'
  patterns:
    entry: 'quick-rise'
    exit: 'fixed-time'

patterns:
  entry:
    quick-rise:
      rise-pct: 0.1
      within-minutes: 5
    quick-fall:
      fall-pct: 0.2
      within-minutes: 5

  exit:
    fixed-time:
      hold-minutes: 10
