default:
  date:
    from: '2017-01-01'
    to: '2025-12-31'
  ticker: 'SPY'
  timeframe: '1min'
  # direction can be 'long', 'short', or 'llm_decides'.
  # If 'llm_decides', llmConfirmationScreen.enabled must be true.
  direction: 'llm_decides'
  patterns:
    entry: 'fixed-time-entry'
  charts:
    generate: true
    outputDir: './charts'
  exitStrategies:
    enabled:
      - profitTarget
      - trailingStop
      - maxHoldTime
      - endOfDay
    # atrPeriodForEntry: 14 # This specific period is NOT used by the current ATR calculation method (which averages all TRs from the prior day).
    # Remove or keep commented if you plan to use a period-specific ATR calc in the future.
    maxHoldTime:
      minutes: 500
    stopLoss:
      # percentFromEntry: 0.5 # Fallback, commented out to prioritize ATR
      atrMultiplier: 2.0 # Default: Stop at 2.0 * Prior Day's Average TR
    profitTarget:
      # percentFromEntry: 0.5 # Fallback, commented out to prioritize ATR
      atrMultiplier: 5.0 # Default: Target 3.0 * Prior Day's Average TR
    trailingStop:
      # activationPercent: 0 # Fallback, commented out to prioritize ATR
      # trailPercent: 0.3      # Fallback, commented out to prioritize ATR (0.3 for 0.3% of price)
      activationAtrMultiplier: 0 # Activate immediately (no favorable movement required)
      trailAtrMultiplier: 2.5 # Default: Trail by 1.0 * Prior Day's Average TR
    endOfDay:
      time: '16:00'
    slippage:
      model: 'fixed'
      value: 0.01

patterns:
  entry:
    quick-rise:
      rise-pct: 0.3
      within-minutes: 5
    quick-fall:
      fall-pct: 0.3
      within-minutes: 5
    fixed-time-entry:
      entry-time: '13:00'

llmConfirmationScreen:
  enabled: true
  llmProvider: 'anthropic'
  modelName: 'claude-3-7-sonnet-latest'
  apiKeyEnvVar: 'ANTHROPIC_API_KEY'
  numCalls: 2
  agreementThreshold: 2
  temperatures: [0.1, 1.0]
  systemPrompt: >-
    You are a seasoned day trader. You know when to save your powder and wait. You don't assume you
    always need to be in the market. Only when you're sure will you go long or short.

    You will be provided with a stock chart for the previous trading day and the current day. Note
    the x-axis dates and times to find the close of the prior day and the open of the current day:
    it is plotted continuously so the day end/start may not be immediately apparent. The current day
    will be incomplete as the trading day is still in progress. Pay careful attention to the current
    day as that is what we are trading. The chart will use candlesticks and volume bars. These are
    key items to pay attention to. Ignore the ticker symbol, current date, etc. We are backtesting a
    strategy so you must focus on generating an action based solely on chart mechanics, not any
    historical knowledge you have of that particular day.

    You strictly follow user instructions for output format. Respond ONLY with the valid JSON object
    described by the user. Do not include any other text, narration, or explanations.
  prompts:
    - You are a seasoned but conservative day trader. You are mindful of sudden reversals,
      continuations, and other interesting patterns.
    - You are a quant trader that still has a knack for spotting patterns and trends. You were top
      of your class at MIT and Stanford.
  #   - You are a YOLO trader that is super-savvy and has exceptional intuition. Your rationale must be in WSB lingo.
  commonPromptSuffixForJson: >-
    Based on the provided chart, what action would you take: go long, go short, or do nothing?
    Provide a one-sentence rationalization for your decision.

    Your response MUST be a valid JSON object and nothing else.  For example: `{"action": "long",
    "rationalization": "<would appear here>"}` or  `{"action": "short", "rationalization": "<would
    appear here>"}` or  `{"action": "do_nothing", "rationalization": "<would appear here>"}`
  maxOutputTokens: 150
